### ISSUE TITLE
Game crashes when pressing "N"

### ISSUE THREAD

**Issue by fesir-cloud** [Tbsc/TbscClick#10]
Game shows screen with "Saving World" Prompt and closes.

At next start following message occurs:

The game crashes while unexpectet error
Error: 
net.minecraftforge.fml.util.ObfuscationReflectionHelper$UnableToFindMethodException: 
java.lang.NoSuchMethodException: net.minecraft.client.gui.components.ChatComponent.m_93787_(net.minecraft.network.chat.Component,int)

[crash-2022-11-06_13.37.05-client.txt](https://github.com/Tbsc/TbscClick/files/9945843/crash-2022-11-06_13.37.05-client.txt)

**Comment by Epicjii** [comment]
A quick and dirty solution is to unbind that key bind and it won’t crash.

**Comment by Tbsc** [comment]
Okay, I think I know what's the problem here. I'll try to fix it this
weekend.

**Comment by Amkiller-010** [comment]
having the same issue here..pressing the n crashes the game.
this is from the crashlog.

> Stacktrace:
	at net.minecraftforge.fml.util.ObfuscationReflectionHelper.findMethod(ObfuscationReflectionHelper.java:151) ~[fmlcore-1.19.2-43.1.47.jar%23159!/:?] {}
	at tbsc.clickmod.Compat.reflInvokeMethod(Compat.java:191) ~[TbscClick-v2.4.0-mc1.19.jar%23155!/:2.4.0] {re:classloading}
	at tbsc.clickmod.impl.TbscClick.sendMessageWithId(TbscClick.java:256) ~[TbscClick-v2.4.0-mc1.19.jar%23155!/:2.4.0] {re:classloading}
	at tbsc.clickmod.Compat.onKeyPressed(Compat.java:111) ~[TbscClick-v2.4.0-mc1.19.jar%23155!/:2.4.0] {re:classloading}
	at tbsc.clickmod.impl.TbscClick.onKeyPressed(TbscClick.java:115) ~[TbscClick-v2.4.0-mc1.19.jar%23155!/:2.4.0] {re:classloading}
	at tbsc.clickmod.impl.__TbscClick_onKeyPressed_Key.invoke(.dynamic) ~[TbscClick-v2.4.0-mc1.19.jar%23155!/:2.4.0] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onKeyInput(ForgeHooksClient.java:753) ~[forge-1.19.2-43.1.47-universal.jar%23163!/:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.optifine.reflect.Reflector.call(Reflector.java:849) ~[OptiFine_1.19.2_HD_U_H9.jar%23164!/:?] {re:classloading}
	at net.optifine.reflect.ReflectorMethod.call(ReflectorMethod.java:133) ~[OptiFine_1.19.2_HD_U_H9.jar%23164!/:?] {re:classloading}
	at net.minecraft.client.KeyboardHandler.m_90893_(KeyboardHandler.java:633) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.KeyboardHandler.lambda$setupCallbacks$7(KeyboardHandler.java:708) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:118) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.KeyboardHandler.lambda$setupCallbacks$8(KeyboardHandler.java:707) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,xf:OptiFine:default}
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23130!/:build 7] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {}
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:198) ~[client-1.19.2-20220805.130853-srg.jar%23158!/:?] {re:classloading,xf:OptiFine:default,re:mixin,xf:OptiFine:default}
-- Affected level --

**Comment by Tbsc** [comment]
Fixed it in 367b5f34, a new version will be up soon.
