### ISSUE TITLE
Game crash when pressing 'n' to change autoclick interval

### ISSUE THREAD

**Issue by PowderedGolem** [Tbsc/TbscClick#12]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2023-05-05 15:09:56
Description: Unexpected error

java.lang.IllegalStateException: Invalid message signature size
	at com.google.common.base.Preconditions.checkState(Preconditions.java:502) ~[guava-31.1-jre.jar%23105!/:?] {}
	at net.minecraft.network.chat.MessageSignature.<init>(MessageSignature.java:26) ~[client-1.19.4-20230314.122934-srg.jar%23164!/:?] {re:classloading}
	at tbsc.clickmod.impl.TbscClick.sendMessageWithId(TbscClick.java:260) ~[TbscClick-v2.4.1-mc1.19.2.jar%23162!/:2.4.1] {re:classloading}
	at tbsc.clickmod.Compat.onKeyPressed(Compat.java:111) ~[TbscClick-v2.4.1-mc1.19.2.jar%23162!/:2.4.1] {re:classloading}
	at tbsc.clickmod.impl.TbscClick.onKeyPressed(TbscClick.java:117) ~[TbscClick-v2.4.1-mc1.19.2.jar%23162!/:2.4.1] {re:classloading}
	at tbsc.clickmod.impl.__TbscClick_onKeyPressed_Key.invoke(.dynamic) ~[TbscClick-v2.4.1-mc1.19.2.jar%23162!/:2.4.1] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onKeyInput(ForgeHooksClient.java:739) ~[forge-1.19.4-45.0.43-universal.jar%23169!/:?] {re:classloading}
	at net.minecraft.client.KeyboardHandler.m_90893_(KeyboardHandler.java:436) ~[client-1.19.4-20230314.122934-srg.jar%23164!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardHandler.m_167831_(KeyboardHandler.java:467) ~[client-1.19.4-20230314.122934-srg.jar%23164!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:102) ~[client-1.19.4-20230314.122934-srg.jar%23164!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.KeyboardHandler.m_90938_(KeyboardHandler.java:466) ~[client-1.19.4-20230314.122934-srg.jar%23164!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) ~[lwjgl-glfw-3.3.1.jar%23137!/:build 7] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23149!/:build 7] {}
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar%23137!/:build 7] {}
	at com.mojang.blaze3d.systems.RenderSystem.m_69830_(RenderSystem.java:234) ~[client-1.19.4-20230314.122934-srg.jar%23164!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1185) ~[client-1.19.4-20230314.122934-srg.jar%23164!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:731) ~[client-1.19.4-20230314.122934-srg.jar%23164!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[1.19.4-forge-45.0.43.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.4-45.0.43.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

**Comment by Tbsc** [comment]
Looks related to issue #10. Likely also related to the mod, compiled for
1.19.2, being run on 1.19.4.
I don't have time to fix this mod, so unfortunately, I can't help now.
